baseURL = 'http://oneapi-community.github.io'
languageCode = 'en-us'
title = 'oneAPI Community Page'
theme = 'projectshowcase-theme'

[params]
sitename = "oneAPI Community"
githubToken = "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"
