baseURL = 'http://oneapi-community.github.io'
languageCode = 'en-us'
title = 'oneAPI Community Page'
theme = 'projectshowcase-theme'

[params]
sitename = "oneAPI Community"

[security]
  [security.funcs]
    getenv = ['^GH_TOKEN']


