name: oneAPIShowCaseCommit
on: 
  push:
    branches:
      - main # trigger deployment when using main branch
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: oneapi-community/oneapi-community.github.io
          publish_dir: ./public
          keep_files: true
          user_name: sramkrishna
          user_email: sri.ramkrishna@intel.com
          publish_branch: main
          cname: oneapi-community.github.io
