name: oneAPIShowCaseCommit
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: oneapi-community/oneapi-community.github.io
          publish_dir: ./public
          keep_files: true
          user_name: sramkrishna
          user_email: sri.ramkrishna@intel.com
          publish_branch: main
          cname: oneapi-community.github.io
